#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 3.1.0.build{build}

image:
  - Visual Studio 2015

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: "C:\\Miniconda"
      MINGW_BIN_PATH: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1\\mingw32\\bin"
      ARCH: "32"
      
    - PYTHON_VERSION: 2.7
      MINICONDA: "C:\\Miniconda-x64"
      MINGW_BIN_PATH: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin"
      ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda create -n _dtocean_hydro python=%PYTHON_VERSION% pip
  - activate _dtocean_hydro
  - copy .condarc %CONDA_PREFIX%
  - conda install polite=0.10.0
  - conda install -y numpy=1.11.3=py27hfef472a_4 libpython
  - python setup.py bootstrap
  - conda install --file requirements-conda-dev.txt
  - pip install -e .
  - conda install dtocean-data
  - conda install mock pytest pytest-cov=2.5.1 pytest-mock

build: off

test_script:
  - python setup.py test -a "--cov dtocean_hydro --cov dtocean_tidal --cov dtocean_wave --cov dtocean_wec"

after_test:
 - pip install codecov
 - codecov
