#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Build only for commits to certain locations
only_commits:
  files:
    - dtocean_hydro/
    - dtocean_tidal/
    - dtocean_wave/
    - dtocean_wec/
    - src/
    - tests/
    - setup.py
    
skip_commits:
  files:
    - dtocean_hydro/config/

# version format
version: 1.1.dev0.build{build}

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: "C:\\Miniconda"
      ARCH: "32"
      
    - PYTHON_VERSION: 2.7
      MINICONDA: "C:\\Miniconda-x64"
      ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda config --append channels conda-forge
  - conda config --append channels dataonlygreater
  - conda info --all
  - "conda create --quiet --name conda-env-%PYTHON_VERSION%-%ARCH% python=%PYTHON_VERSION% --file requirements-conda.txt"
  - activate conda-env-%PYTHON_VERSION%-%ARCH%
  - "copy %MINICONDA%\\envs\\conda-env-%PYTHON_VERSION%-%ARCH%\\libs\\libmsvcr90.a %MINICONDA%\\envs\\conda-env-%PYTHON_VERSION%-%ARCH%\\libs\\libmsvcr90d.a"
  - python setup.py bootstrap
  - python setup.py develop
  
build: off
  
test_script:
  - python setup.py test -a "--cov dtocean_hydro --cov dtocean_tidal --cov dtocean_wave --cov dtocean_wec"
  
after_test:
 - pip install codecov
 - codecov
  
