# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../designer/plotter.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(713, 608)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_plot_update = QtGui.QPushButton(Form)
        self.btn_plot_update.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_plot_update.setObjectName(_fromUtf8("btn_plot_update"))
        self.gridLayout.addWidget(self.btn_plot_update, 0, 0, 1, 2)
        self.mpl_window = QtGui.QWidget(Form)
        self.mpl_window.setObjectName(_fromUtf8("mpl_window"))
        self.mpl_vl = QtGui.QVBoxLayout(self.mpl_window)
        self.mpl_vl.setObjectName(_fromUtf8("mpl_vl"))
        self.gridLayout.addWidget(self.mpl_window, 8, 1, 2, 1)
        self.groupBox_11 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_11.setMaximumSize(QtCore.QSize(120, 16777215))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_26 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.label_52 = QtGui.QLabel(self.groupBox_11)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_26.addWidget(self.label_52, 4, 1, 1, 1)
        self.cb_hm0 = QtGui.QComboBox(self.groupBox_11)
        self.cb_hm0.setObjectName(_fromUtf8("cb_hm0"))
        self.gridLayout_26.addWidget(self.cb_hm0, 5, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_11)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_26.addWidget(self.label_53, 5, 1, 1, 1)
        self.cb_te = QtGui.QComboBox(self.groupBox_11)
        self.cb_te.setObjectName(_fromUtf8("cb_te"))
        self.gridLayout_26.addWidget(self.cb_te, 4, 0, 1, 1)
        self.cb_wavedir = QtGui.QComboBox(self.groupBox_11)
        self.cb_wavedir.setObjectName(_fromUtf8("cb_wavedir"))
        self.gridLayout_26.addWidget(self.cb_wavedir, 6, 0, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox_11)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_26.addWidget(self.label_54, 6, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_11)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_26.addWidget(self.label_16, 0, 1, 1, 1)
        self.cb_dofj = QtGui.QComboBox(self.groupBox_11)
        self.cb_dofj.setObjectName(_fromUtf8("cb_dofj"))
        self.gridLayout_26.addWidget(self.cb_dofj, 1, 0, 1, 1)
        self.cb_dofi = QtGui.QComboBox(self.groupBox_11)
        self.cb_dofi.setObjectName(_fromUtf8("cb_dofi"))
        self.gridLayout_26.addWidget(self.cb_dofi, 0, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.groupBox_11)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_26.addWidget(self.label_50, 1, 1, 1, 1)
        self.cb_angle = QtGui.QComboBox(self.groupBox_11)
        self.cb_angle.setObjectName(_fromUtf8("cb_angle"))
        self.gridLayout_26.addWidget(self.cb_angle, 2, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_11)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_26.addWidget(self.label_51, 2, 1, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_11)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_26.addWidget(self.line, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_11, 9, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.rb_radiation = QtGui.QRadioButton(self.groupBox_9)
        self.rb_radiation.setObjectName(_fromUtf8("rb_radiation"))
        self.verticalLayout_2.addWidget(self.rb_radiation)
        self.rb_excitation = QtGui.QRadioButton(self.groupBox_9)
        self.rb_excitation.setObjectName(_fromUtf8("rb_excitation"))
        self.verticalLayout_2.addWidget(self.rb_excitation)
        self.rb_mass = QtGui.QRadioButton(self.groupBox_9)
        self.rb_mass.setObjectName(_fromUtf8("rb_mass"))
        self.verticalLayout_2.addWidget(self.rb_mass)
        self.rb_stiffness = QtGui.QRadioButton(self.groupBox_9)
        self.rb_stiffness.setObjectName(_fromUtf8("rb_stiffness"))
        self.verticalLayout_2.addWidget(self.rb_stiffness)
        self.c_fit = QtGui.QRadioButton(self.groupBox_9)
        self.c_fit.setObjectName(_fromUtf8("c_fit"))
        self.verticalLayout_2.addWidget(self.c_fit)
        self.k_fit = QtGui.QRadioButton(self.groupBox_9)
        self.k_fit.setObjectName(_fromUtf8("k_fit"))
        self.verticalLayout_2.addWidget(self.k_fit)
        self.rb_origpowermat = QtGui.QRadioButton(self.groupBox_9)
        self.rb_origpowermat.setObjectName(_fromUtf8("rb_origpowermat"))
        self.verticalLayout_2.addWidget(self.rb_origpowermat)
        self.rb_userpowermat = QtGui.QRadioButton(self.groupBox_9)
        self.rb_userpowermat.setObjectName(_fromUtf8("rb_userpowermat"))
        self.verticalLayout_2.addWidget(self.rb_userpowermat)
        self.rb_powermat = QtGui.QRadioButton(self.groupBox_9)
        self.rb_powermat.setObjectName(_fromUtf8("rb_powermat"))
        self.verticalLayout_2.addWidget(self.rb_powermat)
        self.rb_rao = QtGui.QRadioButton(self.groupBox_9)
        self.rb_rao.setObjectName(_fromUtf8("rb_rao"))
        self.verticalLayout_2.addWidget(self.rb_rao)
        self.gridLayout.addWidget(self.groupBox_9, 8, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Data Visualisation - Module", None))
        self.btn_plot_update.setText(_translate("Form", "Update Plot", None))
        self.groupBox_11.setTitle(_translate("Form", "Coefficient Selection", None))
        self.label_52.setText(_translate("Form", "Te", None))
        self.label_53.setText(_translate("Form", "Hm0", None))
        self.label_54.setText(_translate("Form", "Dir  -  ?", None))
        self.label_16.setText(_translate("Form", "dof i", None))
        self.label_50.setText(_translate("Form", "dof j", None))
        self.label_51.setText(_translate("Form", "wave angle  -  ?", None))
        self.groupBox_9.setTitle(_translate("Form", "Plot Selection", None))
        self.rb_radiation.setText(_translate("Form", "Radiation coefficients", None))
        self.rb_excitation.setText(_translate("Form", "Excitation coefficients", None))
        self.rb_mass.setText(_translate("Form", "Mass Matrix", None))
        self.rb_stiffness.setText(_translate("Form", "Hydrostaic Stiffness", None))
        self.c_fit.setText(_translate("Form", "Fit Damping", None))
        self.k_fit.setText(_translate("Form", "Fit Stiffness", None))
        self.rb_origpowermat.setText(_translate("Form", "Original Power Matrix", None))
        self.rb_userpowermat.setText(_translate("Form", "User Power Matrix", None))
        self.rb_powermat.setText(_translate("Form", "Fitted Power Matrix", None))
        self.rb_rao.setText(_translate("Form", "RAO", None))

