# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../designer/read_nemoh_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1090, 748)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.le_data_t3 = QtGui.QLineEdit(Form)
        self.le_data_t3.setObjectName(_fromUtf8("le_data_t3"))
        self.gridLayout.addWidget(self.le_data_t3, 0, 0, 1, 1)
        self.btn_browse_t3 = QtGui.QPushButton(Form)
        self.btn_browse_t3.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_browse_t3.setObjectName(_fromUtf8("btn_browse_t3"))
        self.gridLayout.addWidget(self.btn_browse_t3, 0, 1, 1, 1)
        self.gen_input_2 = QtGui.QGroupBox(Form)
        self.gen_input_2.setObjectName(_fromUtf8("gen_input_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gen_input_2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_26 = QtGui.QLabel(self.gen_input_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_13.addWidget(self.label_26, 2, 2, 1, 2)
        self.label_25 = QtGui.QLabel(self.gen_input_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_13.addWidget(self.label_25, 0, 2, 1, 2)
        self.ndof_t3 = QtGui.QLineEdit(self.gen_input_2)
        self.ndof_t3.setText(_fromUtf8(""))
        self.ndof_t3.setObjectName(_fromUtf8("ndof_t3"))
        self.gridLayout_13.addWidget(self.ndof_t3, 0, 0, 1, 2)
        self.pto_dof_t3 = QtGui.QLineEdit(self.gen_input_2)
        self.pto_dof_t3.setText(_fromUtf8(""))
        self.pto_dof_t3.setObjectName(_fromUtf8("pto_dof_t3"))
        self.gridLayout_13.addWidget(self.pto_dof_t3, 1, 0, 1, 2)
        self.submit_err_t3 = QtGui.QLabel(self.gen_input_2)
        self.submit_err_t3.setText(_fromUtf8(""))
        self.submit_err_t3.setObjectName(_fromUtf8("submit_err_t3"))
        self.gridLayout_13.addWidget(self.submit_err_t3, 16, 2, 2, 2)
        self.moor_dof_t3 = QtGui.QLineEdit(self.gen_input_2)
        self.moor_dof_t3.setText(_fromUtf8(""))
        self.moor_dof_t3.setObjectName(_fromUtf8("moor_dof_t3"))
        self.gridLayout_13.addWidget(self.moor_dof_t3, 2, 0, 1, 2)
        self.label_28 = QtGui.QLabel(self.gen_input_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_13.addWidget(self.label_28, 1, 2, 1, 2)
        self.cb_gen_array_mat_t3 = QtGui.QCheckBox(self.gen_input_2)
        self.cb_gen_array_mat_t3.setObjectName(_fromUtf8("cb_gen_array_mat_t3"))
        self.gridLayout_13.addWidget(self.cb_gen_array_mat_t3, 17, 0, 1, 1)
        self.gridLayout.addWidget(self.gen_input_2, 1, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.sh0_t3 = QtGui.QCheckBox(self.groupBox_5)
        self.sh0_t3.setObjectName(_fromUtf8("sh0_t3"))
        self.gridLayout_14.addWidget(self.sh0_t3, 0, 0, 1, 1)
        self.sh1_t3 = QtGui.QCheckBox(self.groupBox_5)
        self.sh1_t3.setObjectName(_fromUtf8("sh1_t3"))
        self.gridLayout_14.addWidget(self.sh1_t3, 0, 1, 1, 1)
        self.sh2_t3 = QtGui.QCheckBox(self.groupBox_5)
        self.sh2_t3.setObjectName(_fromUtf8("sh2_t3"))
        self.gridLayout_14.addWidget(self.sh2_t3, 0, 2, 1, 1)
        self.sh3_t3 = QtGui.QCheckBox(self.groupBox_5)
        self.sh3_t3.setObjectName(_fromUtf8("sh3_t3"))
        self.gridLayout_14.addWidget(self.sh3_t3, 1, 0, 1, 1)
        self.sh4_t3 = QtGui.QCheckBox(self.groupBox_5)
        self.sh4_t3.setObjectName(_fromUtf8("sh4_t3"))
        self.gridLayout_14.addWidget(self.sh4_t3, 1, 1, 1, 1)
        self.sh5_t3 = QtGui.QCheckBox(self.groupBox_5)
        self.sh5_t3.setObjectName(_fromUtf8("sh5_t3"))
        self.gridLayout_14.addWidget(self.sh5_t3, 1, 2, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_5, 1, 0, 1, 3)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.dof_body_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.dof_body_t3.setObjectName(_fromUtf8("dof_body_t3"))
        self.gridLayout_15.addWidget(self.dof_body_t3, 4, 1, 1, 2)
        self.id_body_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.id_body_t3.setText(_fromUtf8(""))
        self.id_body_t3.setObjectName(_fromUtf8("id_body_t3"))
        self.gridLayout_15.addWidget(self.id_body_t3, 2, 1, 1, 2)
        self.add_err_t3 = QtGui.QLabel(self.groupBox_6)
        self.add_err_t3.setText(_fromUtf8(""))
        self.add_err_t3.setObjectName(_fromUtf8("add_err_t3"))
        self.gridLayout_15.addWidget(self.add_err_t3, 7, 3, 2, 2)
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_15.addWidget(self.label_29, 5, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_6)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_15.addWidget(self.label_30, 3, 1, 1, 1)
        self.mesh_f_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.mesh_f_t3.setText(_fromUtf8(""))
        self.mesh_f_t3.setObjectName(_fromUtf8("mesh_f_t3"))
        self.gridLayout_15.addWidget(self.mesh_f_t3, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_15.addWidget(self.label_31, 1, 1, 1, 1)
        self.parent_body_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.parent_body_t3.setText(_fromUtf8(""))
        self.parent_body_t3.setObjectName(_fromUtf8("parent_body_t3"))
        self.gridLayout_15.addWidget(self.parent_body_t3, 4, 4, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_15.addWidget(self.label_27, 3, 3, 1, 1)
        self.chil_body_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.chil_body_t3.setText(_fromUtf8(""))
        self.chil_body_t3.setObjectName(_fromUtf8("chil_body_t3"))
        self.gridLayout_15.addWidget(self.chil_body_t3, 4, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_15.addWidget(self.label_24, 3, 4, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_15.addWidget(self.label_22, 1, 4, 1, 1)
        self.cs_body_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.cs_body_t3.setText(_fromUtf8(""))
        self.cs_body_t3.setObjectName(_fromUtf8("cs_body_t3"))
        self.gridLayout_15.addWidget(self.cs_body_t3, 2, 4, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_15.addWidget(self.label_23, 1, 3, 1, 1)
        self.mass_body_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.mass_body_t3.setText(_fromUtf8(""))
        self.mass_body_t3.setObjectName(_fromUtf8("mass_body_t3"))
        self.gridLayout_15.addWidget(self.mass_body_t3, 6, 1, 1, 2)
        self.btn_add_body_t3 = QtGui.QPushButton(self.groupBox_6)
        self.btn_add_body_t3.setObjectName(_fromUtf8("btn_add_body_t3"))
        self.gridLayout_15.addWidget(self.btn_add_body_t3, 8, 1, 1, 1)
        self.btn_remove_body_t3 = QtGui.QPushButton(self.groupBox_6)
        self.btn_remove_body_t3.setObjectName(_fromUtf8("btn_remove_body_t3"))
        self.gridLayout_15.addWidget(self.btn_remove_body_t3, 8, 2, 1, 1)
        self.btn_mesh_f_t3 = QtGui.QPushButton(self.groupBox_6)
        self.btn_mesh_f_t3.setObjectName(_fromUtf8("btn_mesh_f_t3"))
        self.gridLayout_15.addWidget(self.btn_mesh_f_t3, 0, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_15.addWidget(self.label_21, 5, 3, 1, 1)
        self.cog_body_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.cog_body_t3.setText(_fromUtf8(""))
        self.cog_body_t3.setObjectName(_fromUtf8("cog_body_t3"))
        self.gridLayout_15.addWidget(self.cog_body_t3, 2, 3, 1, 1)
        self.btn_view_mesh_t3 = QtGui.QPushButton(self.groupBox_6)
        self.btn_view_mesh_t3.setObjectName(_fromUtf8("btn_view_mesh_t3"))
        self.gridLayout_15.addWidget(self.btn_view_mesh_t3, 0, 4, 1, 1)
        self.inertia_body_t3 = QtGui.QLineEdit(self.groupBox_6)
        self.inertia_body_t3.setText(_fromUtf8(""))
        self.inertia_body_t3.setObjectName(_fromUtf8("inertia_body_t3"))
        self.gridLayout_15.addWidget(self.inertia_body_t3, 6, 3, 1, 2)
        self.tab_body_t3 = QtGui.QTableWidget(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_body_t3.sizePolicy().hasHeightForWidth())
        self.tab_body_t3.setSizePolicy(sizePolicy)
        self.tab_body_t3.setWordWrap(False)
        self.tab_body_t3.setObjectName(_fromUtf8("tab_body_t3"))
        self.tab_body_t3.setColumnCount(9)
        self.tab_body_t3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body_t3.setHorizontalHeaderItem(8, item)
        self.gridLayout_15.addWidget(self.tab_body_t3, 9, 1, 1, 4)
        self.gridLayout_12.addWidget(self.groupBox_6, 2, 0, 1, 3)
        self.local_cs_t3 = QtGui.QLineEdit(self.groupBox_4)
        self.local_cs_t3.setText(_fromUtf8(""))
        self.local_cs_t3.setObjectName(_fromUtf8("local_cs_t3"))
        self.gridLayout_12.addWidget(self.local_cs_t3, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_12.addWidget(self.label_32, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 2)
        self.btn_load_data_t3 = QtGui.QPushButton(Form)
        self.btn_load_data_t3.setObjectName(_fromUtf8("btn_load_data_t3"))
        self.gridLayout.addWidget(self.btn_load_data_t3, 4, 1, 1, 1)
        self.btn_submit_t3 = QtGui.QPushButton(Form)
        self.btn_submit_t3.setObjectName(_fromUtf8("btn_submit_t3"))
        self.gridLayout.addWidget(self.btn_submit_t3, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Hydrodynamic - Module", None))
        self.le_data_t3.setPlaceholderText(_translate("Form", "C:\\users\\johndoe\\desktop\\data_nemoh", None))
        self.btn_browse_t3.setText(_translate("Form", "browse Nemoh results", None))
        self.gen_input_2.setTitle(_translate("Form", "general inputs", None))
        self.label_26.setText(_translate("Form", "ID of the independent degree of freedoms connected to the mooring  -  ? ", None))
        self.label_25.setText(_translate("Form", "number of independent degree of freedoms  -  ?", None))
        self.ndof_t3.setPlaceholderText(_translate("Form", "6", None))
        self.pto_dof_t3.setPlaceholderText(_translate("Form", "1, 3", None))
        self.moor_dof_t3.setPlaceholderText(_translate("Form", "1, 2", None))
        self.label_28.setText(_translate("Form", "ID of the independent degree of freedoms connected to the PTO  -  ? ", None))
        self.cb_gen_array_mat_t3.setText(_translate("Form", "load array interaction matrices", None))
        self.groupBox_4.setTitle(_translate("Form", "Body desciption", None))
        self.groupBox_5.setTitle(_translate("Form", "degrees of freedom of the floating body", None))
        self.sh0_t3.setText(_translate("Form", "Surge", None))
        self.sh1_t3.setText(_translate("Form", "Sway", None))
        self.sh2_t3.setText(_translate("Form", "Heave", None))
        self.sh3_t3.setText(_translate("Form", "Roll", None))
        self.sh4_t3.setText(_translate("Form", "Pitch", None))
        self.sh5_t3.setText(_translate("Form", "Yaw", None))
        self.groupBox_6.setTitle(_translate("Form", "single body specification", None))
        self.dof_body_t3.setPlaceholderText(_translate("Form", "1, 1, 0, 0 ; 2, 0, 1, 0 (if any)", None))
        self.id_body_t3.setPlaceholderText(_translate("Form", "0", None))
        self.label_29.setText(_translate("Form", "body mass [kg]", None))
        self.label_30.setText(_translate("Form", "relative DoF(s) between body and parent [dof type, ax, ay, az ]  ", None))
        self.mesh_f_t3.setPlaceholderText(_translate("Form", "C:\\users\\johndoe\\desktop\\cylinder.gdf", None))
        self.label_31.setText(_translate("Form", "ID", None))
        self.parent_body_t3.setPlaceholderText(_translate("Form", "-1", None))
        self.label_27.setText(_translate("Form", "child(s) [child ID, child CS position (x,y,z) [m]]", None))
        self.chil_body_t3.setPlaceholderText(_translate("Form", "1, 10, 0, -1 ; 2, 6, 0, -1 (if any)", None))
        self.label_24.setText(_translate("Form", "Parent body ID (-1 if none)", None))
        self.label_22.setText(_translate("Form", "body CS orientation (euler angles [deg])", None))
        self.cs_body_t3.setPlaceholderText(_translate("Form", "0,0,0", None))
        self.label_23.setText(_translate("Form", "CoG with respect to the body CS [m]", None))
        self.mass_body_t3.setPlaceholderText(_translate("Form", "1", None))
        self.btn_add_body_t3.setText(_translate("Form", "Add", None))
        self.btn_remove_body_t3.setText(_translate("Form", "Remove Selected Row", None))
        self.btn_mesh_f_t3.setText(_translate("Form", "browse", None))
        self.label_21.setText(_translate("Form", "body moment of inertia tensor [3x3] expressed in the body CoG [kgm^2]", None))
        self.cog_body_t3.setPlaceholderText(_translate("Form", "0,0,0", None))
        self.btn_view_mesh_t3.setText(_translate("Form", "View", None))
        self.inertia_body_t3.setPlaceholderText(_translate("Form", "10, 0, 0; 0, 10, 0; 0, 0, 2", None))
        item = self.tab_body_t3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID", None))
        item = self.tab_body_t3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "mass", None))
        item = self.tab_body_t3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "inertia", None))
        item = self.tab_body_t3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "mesh", None))
        item = self.tab_body_t3.horizontalHeaderItem(4)
        item.setText(_translate("Form", "CoG", None))
        item = self.tab_body_t3.horizontalHeaderItem(5)
        item.setText(_translate("Form", "CS orientation", None))
        item = self.tab_body_t3.horizontalHeaderItem(6)
        item.setText(_translate("Form", "DoF(s) with parent", None))
        item = self.tab_body_t3.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Child ID and position", None))
        item = self.tab_body_t3.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Parent body ID", None))
        self.local_cs_t3.setPlaceholderText(_translate("Form", "0,0,0", None))
        self.label_32.setText(_translate("Form", "point of application of the equation of motion expressed in the global CS (mesh file)                                                ", None))
        self.btn_load_data_t3.setText(_translate("Form", "Load Data", None))
        self.btn_submit_t3.setText(_translate("Form", "Submit Inputs", None))

