# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../designer/run_nemoh_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(969, 921)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gen_input = QtGui.QGroupBox(Form)
        self.gen_input.setObjectName(_fromUtf8("gen_input"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gen_input)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fre_def = QtGui.QLineEdit(self.gen_input)
        self.fre_def.setText(_fromUtf8(""))
        self.fre_def.setObjectName(_fromUtf8("fre_def"))
        self.gridLayout_3.addWidget(self.fre_def, 10, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.gen_input)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 10, 2, 1, 2)
        self.label_2 = QtGui.QLabel(self.gen_input)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 2)
        self.ndof = QtGui.QLineEdit(self.gen_input)
        self.ndof.setText(_fromUtf8(""))
        self.ndof.setObjectName(_fromUtf8("ndof"))
        self.gridLayout_3.addWidget(self.ndof, 0, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.gen_input)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 2, 1, 2)
        self.pto_dof = QtGui.QLineEdit(self.gen_input)
        self.pto_dof.setText(_fromUtf8(""))
        self.pto_dof.setObjectName(_fromUtf8("pto_dof"))
        self.gridLayout_3.addWidget(self.pto_dof, 1, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.gen_input)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 17, 2, 1, 1)
        self.moor_dof = QtGui.QLineEdit(self.gen_input)
        self.moor_dof.setText(_fromUtf8(""))
        self.moor_dof.setObjectName(_fromUtf8("moor_dof"))
        self.gridLayout_3.addWidget(self.moor_dof, 2, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.gen_input)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 2, 1, 2)
        self.angles_def = QtGui.QLineEdit(self.gen_input)
        self.angles_def.setText(_fromUtf8(""))
        self.angles_def.setObjectName(_fromUtf8("angles_def"))
        self.gridLayout_3.addWidget(self.angles_def, 17, 0, 1, 2)
        self.submit_err_t2 = QtGui.QLabel(self.gen_input)
        self.submit_err_t2.setText(_fromUtf8(""))
        self.submit_err_t2.setObjectName(_fromUtf8("submit_err_t2"))
        self.gridLayout_3.addWidget(self.submit_err_t2, 19, 2, 2, 2)
        self.label_19 = QtGui.QLabel(self.gen_input)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 18, 2, 1, 1)
        self.sb_water_depth = QtGui.QDoubleSpinBox(self.gen_input)
        self.sb_water_depth.setMaximum(999.0)
        self.sb_water_depth.setObjectName(_fromUtf8("sb_water_depth"))
        self.gridLayout_3.addWidget(self.sb_water_depth, 18, 0, 1, 2)
        self.verticalLayout.addWidget(self.gen_input)
        self.gr_array_mat = QtGui.QGroupBox(Form)
        self.gr_array_mat.setObjectName(_fromUtf8("gr_array_mat"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gr_array_mat)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cb_gen_array_mat = QtGui.QCheckBox(self.gr_array_mat)
        self.cb_gen_array_mat.setObjectName(_fromUtf8("cb_gen_array_mat"))
        self.gridLayout_8.addWidget(self.cb_gen_array_mat, 0, 0, 1, 1)
        self.gr_cyl_spec = QtGui.QGroupBox(self.gr_array_mat)
        self.gr_cyl_spec.setEnabled(True)
        self.gr_cyl_spec.setObjectName(_fromUtf8("gr_cyl_spec"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gr_cyl_spec)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.sb_nzeta = QtGui.QSpinBox(self.gr_cyl_spec)
        self.sb_nzeta.setMinimum(10)
        self.sb_nzeta.setMaximum(1000)
        self.sb_nzeta.setObjectName(_fromUtf8("sb_nzeta"))
        self.gridLayout_9.addWidget(self.sb_nzeta, 0, 0, 1, 1)
        self.sb_ntheta = QtGui.QSpinBox(self.gr_cyl_spec)
        self.sb_ntheta.setMinimum(10)
        self.sb_ntheta.setMaximum(1000)
        self.sb_ntheta.setObjectName(_fromUtf8("sb_ntheta"))
        self.gridLayout_9.addWidget(self.sb_ntheta, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.gr_cyl_spec)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_9.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.gr_cyl_spec)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_9.addWidget(self.label_18, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.gr_cyl_spec, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.gr_array_mat)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sh0 = QtGui.QCheckBox(self.groupBox_2)
        self.sh0.setObjectName(_fromUtf8("sh0"))
        self.gridLayout_5.addWidget(self.sh0, 0, 0, 1, 1)
        self.sh1 = QtGui.QCheckBox(self.groupBox_2)
        self.sh1.setObjectName(_fromUtf8("sh1"))
        self.gridLayout_5.addWidget(self.sh1, 0, 1, 1, 1)
        self.sh2 = QtGui.QCheckBox(self.groupBox_2)
        self.sh2.setObjectName(_fromUtf8("sh2"))
        self.gridLayout_5.addWidget(self.sh2, 0, 2, 1, 1)
        self.sh3 = QtGui.QCheckBox(self.groupBox_2)
        self.sh3.setObjectName(_fromUtf8("sh3"))
        self.gridLayout_5.addWidget(self.sh3, 1, 0, 1, 1)
        self.sh4 = QtGui.QCheckBox(self.groupBox_2)
        self.sh4.setObjectName(_fromUtf8("sh4"))
        self.gridLayout_5.addWidget(self.sh4, 1, 1, 1, 1)
        self.sh5 = QtGui.QCheckBox(self.groupBox_2)
        self.sh5.setObjectName(_fromUtf8("sh5"))
        self.gridLayout_5.addWidget(self.sh5, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.btn_mesh_f_t2 = QtGui.QPushButton(self.groupBox_3)
        self.btn_mesh_f_t2.setObjectName(_fromUtf8("btn_mesh_f_t2"))
        self.gridLayout_6.addWidget(self.btn_mesh_f_t2, 0, 3, 1, 1)
        self.btn_view_mesh = QtGui.QPushButton(self.groupBox_3)
        self.btn_view_mesh.setObjectName(_fromUtf8("btn_view_mesh"))
        self.gridLayout_6.addWidget(self.btn_view_mesh, 0, 4, 1, 1)
        self.inertia_body = QtGui.QLineEdit(self.groupBox_3)
        self.inertia_body.setText(_fromUtf8(""))
        self.inertia_body.setObjectName(_fromUtf8("inertia_body"))
        self.gridLayout_6.addWidget(self.inertia_body, 6, 3, 1, 2)
        self.cog_body = QtGui.QLineEdit(self.groupBox_3)
        self.cog_body.setText(_fromUtf8(""))
        self.cog_body.setObjectName(_fromUtf8("cog_body"))
        self.gridLayout_6.addWidget(self.cog_body, 2, 3, 1, 1)
        self.cs_body = QtGui.QLineEdit(self.groupBox_3)
        self.cs_body.setText(_fromUtf8(""))
        self.cs_body.setObjectName(_fromUtf8("cs_body"))
        self.gridLayout_6.addWidget(self.cs_body, 2, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 3, 1, 1)
        self.chil_body = QtGui.QLineEdit(self.groupBox_3)
        self.chil_body.setText(_fromUtf8(""))
        self.chil_body.setObjectName(_fromUtf8("chil_body"))
        self.gridLayout_6.addWidget(self.chil_body, 4, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 3, 4, 1, 1)
        self.parent_body = QtGui.QLineEdit(self.groupBox_3)
        self.parent_body.setText(_fromUtf8(""))
        self.parent_body.setObjectName(_fromUtf8("parent_body"))
        self.gridLayout_6.addWidget(self.parent_body, 4, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 3, 3, 1, 1)
        self.tab_body = QtGui.QTableWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_body.sizePolicy().hasHeightForWidth())
        self.tab_body.setSizePolicy(sizePolicy)
        self.tab_body.setMinimumSize(QtCore.QSize(0, 50))
        self.tab_body.setMaximumSize(QtCore.QSize(16777215, 600))
        self.tab_body.setWordWrap(False)
        self.tab_body.setObjectName(_fromUtf8("tab_body"))
        self.tab_body.setColumnCount(9)
        self.tab_body.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tab_body.setHorizontalHeaderItem(8, item)
        self.gridLayout_6.addWidget(self.tab_body, 9, 1, 1, 4)
        self.btn_add_body = QtGui.QPushButton(self.groupBox_3)
        self.btn_add_body.setObjectName(_fromUtf8("btn_add_body"))
        self.gridLayout_6.addWidget(self.btn_add_body, 8, 1, 1, 1)
        self.btn_remove_body = QtGui.QPushButton(self.groupBox_3)
        self.btn_remove_body.setObjectName(_fromUtf8("btn_remove_body"))
        self.gridLayout_6.addWidget(self.btn_remove_body, 8, 2, 1, 1)
        self.mass_body = QtGui.QLineEdit(self.groupBox_3)
        self.mass_body.setText(_fromUtf8(""))
        self.mass_body.setObjectName(_fromUtf8("mass_body"))
        self.gridLayout_6.addWidget(self.mass_body, 6, 1, 1, 2)
        self.dof_body = QtGui.QLineEdit(self.groupBox_3)
        self.dof_body.setObjectName(_fromUtf8("dof_body"))
        self.gridLayout_6.addWidget(self.dof_body, 4, 1, 1, 2)
        self.id_body = QtGui.QLineEdit(self.groupBox_3)
        self.id_body.setText(_fromUtf8(""))
        self.id_body.setObjectName(_fromUtf8("id_body"))
        self.gridLayout_6.addWidget(self.id_body, 2, 1, 1, 2)
        self.add_err_t2 = QtGui.QLabel(self.groupBox_3)
        self.add_err_t2.setText(_fromUtf8(""))
        self.add_err_t2.setObjectName(_fromUtf8("add_err_t2"))
        self.gridLayout_6.addWidget(self.add_err_t2, 7, 3, 2, 2)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 1, 1, 1)
        self.mesh_f_t2 = QtGui.QLineEdit(self.groupBox_3)
        self.mesh_f_t2.setText(_fromUtf8(""))
        self.mesh_f_t2.setObjectName(_fromUtf8("mesh_f_t2"))
        self.gridLayout_6.addWidget(self.mesh_f_t2, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 5, 3, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 3)
        self.local_cs = QtGui.QLineEdit(self.groupBox)
        self.local_cs.setText(_fromUtf8(""))
        self.local_cs.setObjectName(_fromUtf8("local_cs"))
        self.gridLayout_4.addWidget(self.local_cs, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.btn_submit_t2 = QtGui.QPushButton(Form)
        self.btn_submit_t2.setObjectName(_fromUtf8("btn_submit_t2"))
        self.verticalLayout.addWidget(self.btn_submit_t2)
        self.btn_calculate_t2 = QtGui.QPushButton(Form)
        self.btn_calculate_t2.setObjectName(_fromUtf8("btn_calculate_t2"))
        self.verticalLayout.addWidget(self.btn_calculate_t2)
        self.btn_stop_calculation_t2 = QtGui.QPushButton(Form)
        self.btn_stop_calculation_t2.setObjectName(_fromUtf8("btn_stop_calculation_t2"))
        self.verticalLayout.addWidget(self.btn_stop_calculation_t2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Hydrodynamic - Module", None))
        self.gen_input.setTitle(_translate("Form", "general inputs", None))
        self.fre_def.setPlaceholderText(_translate("Form", "10,    0.4,   8.1", None))
        self.label_5.setText(_translate("Form", "number of frequencies to analyse, min frequency, max frequency [rad/s]", None))
        self.label_2.setText(_translate("Form", "total number of independent degree of freedoms  -  ?", None))
        self.ndof.setPlaceholderText(_translate("Form", "6", None))
        self.label_4.setText(_translate("Form", "ID of the independent degree of freedoms connected to the mooring  -  ?", None))
        self.pto_dof.setPlaceholderText(_translate("Form", "1, 3", None))
        self.label_6.setText(_translate("Form", "number of angles to wave analyse", None))
        self.moor_dof.setPlaceholderText(_translate("Form", "1", None))
        self.label_3.setText(_translate("Form", "ID of the independent degree of freedoms connected to the PTO  -  ?", None))
        self.angles_def.setPlaceholderText(_translate("Form", "11", None))
        self.label_19.setText(_translate("Form", "water depth [m]. Note: 0m water depth is used for the  infinite water depth case", None))
        self.gr_array_mat.setTitle(_translate("Form", "Array Interaction", None))
        self.cb_gen_array_mat.setText(_translate("Form", "generate array interaction matrixes", None))
        self.gr_cyl_spec.setTitle(_translate("Form", "Cylinder specification ", None))
        self.label_17.setText(_translate("Form", "Number of steps in the vertical dimension", None))
        self.label_18.setText(_translate("Form", "Number of steps in the angular dimension", None))
        self.groupBox.setTitle(_translate("Form", "Body desciption", None))
        self.groupBox_2.setTitle(_translate("Form", "degrees of freedom of the floating body", None))
        self.sh0.setText(_translate("Form", "Surge", None))
        self.sh1.setText(_translate("Form", "Sway", None))
        self.sh2.setText(_translate("Form", "Heave", None))
        self.sh3.setText(_translate("Form", "Roll", None))
        self.sh4.setText(_translate("Form", "Pitch", None))
        self.sh5.setText(_translate("Form", "Yaw", None))
        self.groupBox_3.setTitle(_translate("Form", "single body specification", None))
        self.btn_mesh_f_t2.setText(_translate("Form", "browse mesh file", None))
        self.btn_view_mesh.setText(_translate("Form", "View mesh", None))
        self.inertia_body.setPlaceholderText(_translate("Form", "10, 0, 0; 0, 10, 0; 0, 0, 2", None))
        self.cog_body.setPlaceholderText(_translate("Form", "0,0,0", None))
        self.cs_body.setPlaceholderText(_translate("Form", "0,0,0", None))
        self.label_9.setText(_translate("Form", "body CS orientation (euler angles [deg])", None))
        self.label_8.setText(_translate("Form", "CoG with respect to the body CS [m]", None))
        self.chil_body.setPlaceholderText(_translate("Form", "1, 10, 0, -1 ; 2, 6, 0, -1 (if any)", None))
        self.label_12.setText(_translate("Form", "Parent body ID (-1 if none)", None))
        self.parent_body.setPlaceholderText(_translate("Form", "-1", None))
        self.label_11.setText(_translate("Form", "child(s) [child ID, child CS position (x,y,z) [m]]", None))
        item = self.tab_body.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID", None))
        item = self.tab_body.horizontalHeaderItem(1)
        item.setText(_translate("Form", "mass", None))
        item = self.tab_body.horizontalHeaderItem(2)
        item.setText(_translate("Form", "inertia", None))
        item = self.tab_body.horizontalHeaderItem(3)
        item.setText(_translate("Form", "mesh", None))
        item = self.tab_body.horizontalHeaderItem(4)
        item.setText(_translate("Form", "CoG", None))
        item = self.tab_body.horizontalHeaderItem(5)
        item.setText(_translate("Form", "CS orientation", None))
        item = self.tab_body.horizontalHeaderItem(6)
        item.setText(_translate("Form", "DoF(s) with parent", None))
        item = self.tab_body.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Child ID and position", None))
        item = self.tab_body.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Parent body ID", None))
        self.btn_add_body.setText(_translate("Form", "Add body description", None))
        self.btn_remove_body.setText(_translate("Form", "Remove selected body", None))
        self.mass_body.setPlaceholderText(_translate("Form", "1", None))
        self.dof_body.setPlaceholderText(_translate("Form", "1, 1, 0, 0 ; 2, 0, 1, 0 (if any)", None))
        self.id_body.setPlaceholderText(_translate("Form", "0", None))
        self.label_13.setText(_translate("Form", "body mass [kg]", None))
        self.label_7.setText(_translate("Form", "ID", None))
        self.mesh_f_t2.setPlaceholderText(_translate("Form", "C:\\users\\johndoe\\desktop\\cylinder.gdf", None))
        self.label_10.setText(_translate("Form", "relative DoF(s) between body and parent [dof type, ax, ay, az ]  ", None))
        self.label_14.setText(_translate("Form", "body moment of inertia tensor [3x3] expressed in the body CoG [kgm^2]", None))
        self.local_cs.setPlaceholderText(_translate("Form", "0,0,0", None))
        self.label_15.setText(_translate("Form", "point of application of the equation of motion expressed in the global CS (mesh file)                                                ", None))
        self.btn_submit_t2.setText(_translate("Form", "Submit Inputs", None))
        self.btn_calculate_t2.setText(_translate("Form", "Calculate", None))
        self.btn_stop_calculation_t2.setText(_translate("Form", "Interrupt", None))

